### ISSUE TITLE
unextendable PUT request

### ISSUE THREAD

**Issue by ttomttom** [jglobus/JGlobus#154]
The put(...) method in the MyProxy.java class is implemented such that the CSR received from the MyProxy server is never seen. I would like to get this CSR from the put() method sign it somewhere else and return it to the put() method. The obvious choice is to extend the class and write the method myself! The problem is that helper methods and static constants within MyProxy.java (such as handleReply,getSocket...) are all 'private' and cannot be used in the extended class. Could these methods and static constants become 'protected' such that extending the MyProxy.java class would not require so much code duplication?

**Comment by jbasney** [comment]
Sounds good to me. Pull request welcome.
